### ISSUE TITLE
Index.html ist nicht aktuell

### ISSUE THREAD

**Issue by Philipp97714** [fsr/ese-website#101]
Auf der aktuellen ESE Seite ist ein Schreibfehler, der hier im Repo schon vor 2 Jahren gefixt wurde;
https://github.com/fsr/ese-website/blame/development/sources/index.md Zeile 21. Auf der FSR Seite wird das I von Medieninformatik groß geschrieben.

**Comment by Philipp97714** [comment]
Okay bei der Schriftart gibt es offensichtlich kein kleines i.

**Comment by phanpatrik** [comment]
Ein kleines „i“ gibt es schon. Die Frage ist, wie die Font in deinem Browser gerendert wird. Kannst ja mal bei Gelegenheit ein Screenshot zukommen lassen. 🙂

**Comment by Philipp97714** [comment]
@phanpatrik 
![image](https://user-images.githubusercontent.com/12154508/66266748-5e01f300-e829-11e9-8206-d6c356b02990.png)
So sieht es in Chrome und Edge aus

**Comment by phanpatrik** [comment]
Okay liegt einfach am Schriftschnitt in der darstellten Größe. :) Der Punkt vom i ist einfach optisch sehr nah am Strich. Wenn du die Font vergrößerst sieht man es. 👍
