### ISSUE TITLE
Improving Websiteperformance

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-website#19]
[Page Speed Insigt](https://developers.google.com/speed/pagespeed/insights/?url=ese.ifsr.de) brings a good overview what needs some improvements.

What we definitely have to do:  
* Switch on caching
* Switch on compression
* Compress files (I refer to the result from [gh-pages](https://developers.google.com/speed/pagespeed/insights/?url=fsr.github.io/ese-webseite) )

I can provide a example configuration for apache regarding caching and compression.    
For file compression it should be enough to fix the whitespace problems mentioned in #17. I think we can easily switch to a compressed version of the modernizr. I think the konami compression does not need to be done because it would only result in 568 Byte less.

**Comment by MarauderXtreme** [comment]
8d3188ece4164e9728e160fd6c2b957251d03d05 relates the compression.

**Comment by MarauderXtreme** [comment]
Would you kindly configure the Apache correctly? Compression and Caching. I can provide examples that I use on my own website for that.

**Comment by sebschrader** [comment]
Tell me, what you need/want. Which headers, which compression algorithms, which caching method (ETag vs. Expire)

**Comment by kiliankoe** [comment]
> Tell me, what you need/want.

![](https://40.media.tumblr.com/be4dc965e1e5412beb72d70f6fa5ff0c/tumblr_inline_nulguhJ5tV1ri0pk0_540.png)


(sry^^)

**Comment by MarauderXtreme** [comment]
Brotli would be really nice but I think DEFLATE is okay. So here we go.

Compression
----------------

AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/svg
AddOutputFilterByType DEFLATE text/css

AddOutputFilterByType DEFLATE image/svg+xml

AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript

BrowserMatch ^Mozilla/4 gzip-only-text/html
BrowserMatch ^Mozilla/4\.0[678] no-gzip
BrowserMatch \bMSIE !no-gzip !gzip-only-text/html

Header append Vary User-Agent

Caching
----------

ExpiresActive On
ExpiresByType image/jpg                 "access 1 month"
ExpiresByType image/jpeg                "access 1 month"
ExpiresByType image/gif                 "access 1 month"
ExpiresByType image/png                 "access 1 month"
ExpiresByType image/svg+xml             "access 1 month"
ExpiresByType text/svg      "access 1 month"
ExpiresByType application/pdf           "access 1 month"
ExpiresByType image/x-icon    "access 1 month"
ExpiresByType text/css                  "access 1 week"
ExpiresByType application/javascript    "access 1 week"
ExpiresByType application/x-javascript  "access 1 week"
ExpiresByType text/javascript           "access 1 week"
ExpiresByType text/x-javascript         "access 1 week"
ExpiresDefault                          "access 1 week"

**Comment by dirkonet** [comment]
Are cache times of 1 week/1 month useful for a website that will change several times within a few days in late September/early October, including minor fixes to pdfs, tables,…?

**Comment by sebschrader** [comment]
I would prefer using ETags based on hashes of the static files. Since we're not serving dynamic content, ETag seems perfect to me.

**Comment by MarauderXtreme** [comment]
Okay. Well. Than please consider to enligthen me, how this works. I have no clue how to use ETag. ^^

@dirkonet you're right. I forgot this. These were just the references I used.
@sebschrader can we use the same periods with the ETag method?

**Comment by sebschrader** [comment]
The ETag method actually solves the issue @dirkonet mentioned, that's why I prefer them. There are no periods with ETag. If a resource changes, its ETag changes.

Please see https://en.wikipedia.org/wiki/HTTP_ETag if you want to be enlightened

**Comment by MarauderXtreme** [comment]
Okay. How do we assign the hashes to the files?

**Comment by sebschrader** [comment]
It's up to the web server or web application how to provide a ETag. My statement about the hashes was wrong, Apache is actually meta-data, such as the modification date https://httpd.apache.org/docs/2.4/mod/core.html#fileetag

Enabling the FileETag option be everything we need to do.

**Comment by MarauderXtreme** [comment]
So now what? Do you need anything from us or do you just do some black magic and it fixes itself?

**Comment by sebschrader** [comment]
After some further research, I came to the conclusion that we still need `Expires` headers in addition to ETag or Last-Modified.

ETag or Last-Modified will of course only cause the server to respond with `304` responses after the client makes a request with `If-None-Match` or `If-Modified-Since` headers respectively. The client will still make a request. If you want the client to make no requests at all, we need the `Expires` headers in addition.

But I'm with @dirkonet on the duration. Do you really think @MarauderXtreme months and weeks are a good duration? During development, caching is usually a pain in the butt and during ESE you want to change things very often.

And another question? Won't Jekyll recreate all files if you start a new build, even the ones that haven't changed? This would imply that the mtimes of all files will change and the web server will think a new version is available even though the content hasn't changed actually.

**Comment by MarauderXtreme** [comment]
Well. We still have [ctrl] + [f5] to develop. If jekyll regenerates them and the ETag changes than we should be fine with the Expire periods I posted.
This is more or less a request for SEO because we get better ratings if we switch on these things with reasonable periods. (These periods assume a normal website not a dev site)

**Comment by sebschrader** [comment]
Why are we fine then?

**Comment by sebschrader** [comment]
So what do we do now?

Only `ETag` headers will still result in browsers making requests with `If-None-Match` or `If-Modified-Since` and probably won't improve SEO, but I'm not sure, not SEO expert.

Adding `Expires` headers in addition will result in browsers not making any request at all and may improve SEO ratings.

`Expires` headers with more than a few hours are no really reasonable however for a site, which will accessed mostly during the ESE week and **will change** quite a few times during that week.

**Comment by sebschrader** [comment]
I would suggest that we add `Expires` headers only for our resources like JS and images.

Could Jekyll generate unique filenames for these? For example a filename that is based on the md5 hash of the file?

**Comment by MarauderXtreme** [comment]
I think we can just add the hash as a request parameter to the file.
`example.site/css/app.css#hash`
This should be enough for a unique name.

**Comment by sebschrader** [comment]
If Jekyll could do that, great. Then we could set really high values for `Expires` for our resources.

**Comment by sebschrader** [comment]
You probably mean this `example.site/css/app.css?hash`

**Comment by MarauderXtreme** [comment]
I think they both work but I'm not 100% sure. Yours looks better since the # only identifies an anchor within the site.

I am not sure, if jekyll or liquid can do this. My suggestion was instead of generating different file names just adding a unique parameter.

**Comment by MarauderXtreme** [comment]
@sebschrader I've updated the files a bit, so that we have the hash behind every cacheable ressource.

**Comment by sebschrader** [comment]
Caching and compression are now enabled

These are settings that I used:
```apache
# Caching
ExpiresActive On
ExpiresDefault "access 10 minute"
ExpiresByType image/jpg "access 1 year"
ExpiresByType image/jpeg "access 1 year"
ExpiresByType image/gif "access 1 year"
ExpiresByType image/png "access 1 year"
ExpiresByType image/svg+xml "access 1 year"
ExpiresByType text/svg "access 1 year"
ExpiresByType image/x-icon "access 1 year"
ExpiresByType text/css "access 1 week"
ExpiresByType application/javascript "access 1 week"
ExpiresByType application/x-javascript "access 1 week"
ExpiresByType text/javascript "access 1 week"
ExpiresByType text/x-javascript "access 1 week"

# Compression
AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/svg
AddOutputFilterByType DEFLATE text/css

AddOutputFilterByType DEFLATE image/svg+xml

AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript

BrowserMatch ^Mozilla/4 gzip-only-text/html
BrowserMatch ^Mozilla/4.0[678] no-gzip
BrowserMatch \bMSIE !no-gzip !gzip-only-text/html

Header append Vary User-Agent
```

I've sticked to your suggestion mostly, except
* lower default expires value of only 10 minutes
* PDF files use the default expires value as these are probably things like timetables which we should guarantee that they are up to date
* 1 month expires value are increased to 1 year
