### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by kiliankoe** [fsr/ese-website#30]
This is less of an issue for this project, more of a discussion for how the deployment works.

As far as I know the site is generated locally and then sent to an admin to update on the server. Optimizing this would make updates so much easier.

Ideally the workflow would be pushing to a branch on this repo and having that deploy to the server automatically. Protected branches and deployment options similar to `octopress deploy` or `git deploy` might be a good option. Thoughts on what the best course of action could be here?

**Comment by JustusAdam** [comment]
The issue I face currently is that I the server people have not yet agreed to install jekyll on the server.

Should they do so we can start thinking about deploying an endpoint for a commit or better release hook for github.

**Comment by JustusAdam** [comment]
Perhaps @sjmielke and @sebschrader can say something about that.

**Comment by MarauderXtreme** [comment]
We definitely need this asap that we can fix issue like #29 faster.

**Comment by JustusAdam** [comment]
We have conceived a unix grep-chain for filtering all files which should be removed during deployment

    grep -v "^[0-9]\{1,2\}$" | grep -v "^linkCreator\.sh$" | grep -v "^eva$" | grep -v "^nopanic[0-9]*\.pdf$"

We can use this in conjunction with `rm` to remove all generated files, it'll exclude all (currently) manually placed files (such as the "eva").
And then we can just recompile the site and copy all generated html. @sjmielke should deal with this, he got so butthurt last time I touched the deployment process. He probably understands that abomination of an link system.

**Comment by MarauderXtreme** [comment]
@sebschrader You have resurected the deploy hook. Have you also includes the things mentionend in the previous post? Than you can close this issue.

**Comment by sebschrader** [comment]
I don't like the idea of dropping a random hard-coded `grep` somewhere in the deployment hook. Not just because `find` would actually be right tool for this job, but mainly because the deployment hook is not part of the sources and as such it's effects should not be surprising.

What if new/other files need to be preserved? As #29 shows it's not immediately obvious that the deployment was the problem.

So I propose the following two alternatives:

1. Delete everything in the target directory before copying the newly build version and keep files that are mentioned in a `.gitignore` like whitelist that is stored in the repository.
2. Keep everything in the target before except files mentioned in a `.gitignore` like blacklist that is stored in the repository.

I favor the whitelist approach, the only problem is that you could delete files by accident and would only notice it after the fact.

**Comment by sjmielke** [comment]
Different idea, if writing our code is an option: let Jekyll handle all "other" files as well, i.e., let it generate the link list and serve the NoPanic as a static file. Should be easy, if it's anything like Hakyll - but of course that will might the github-pages integration.

**Comment by JustusAdam** [comment]
I don't think a link list or static files is a problem. But isn't there PHP  code there handling the eva?

**Comment by sebschrader** [comment]
PHP files can be treated just like static files. Apache will execute instead of serving them That is one of the “advantages” of PHP. This time it is actually an advantage.

**Comment by sjmielke** [comment]
I guess we could serve everything as these "static files" - then one of you grand code beauty masters will just have to figure out how to do that in a clean way. :) My ~50 bash-script-generated PHP files (i.e. the linklist) are not a clean way and I wouldn't feel very... comfortable adding them to the ese-website repo :D And the ESE-EVA is it's own separate repo as well - and that's how it should be kept IMO.

**Comment by sebschrader** [comment]
I do very much like @sjmielke's idea. EVA could be included as a git submodule.

**Comment by sjmielke** [comment]
Only "downside": each EVA commit would require a website rebuild, but... that hopefully won't be needed very often.

**Comment by sebschrader** [comment]
There are still files that would need to be preserved, right? The EVA database for example.

**Comment by sjmielke** [comment]
We can just save it in a whole different directory, I think. Or maybe create a subdirectory "permament" that is excluded from the pre-build purging. We could even put the whole EVA somewhere else and let Apache rewrite magic lead our users there, but keeping all of 2016 in `/2016` has its appeal.

**Comment by sebschrader** [comment]
Jekyll has a [`keep_files` option](https://jekyllrb.com/docs/configuration/). This could be used.

**Comment by sebschrader** [comment]
Looks like we agree, that all contents should be handled by Jekyll. This means

* `eva` should be made a git submodule
* the `eva` database must be put into Jekyll's `keep_files` option
* the no panic PDF files would have to be imported into the ese-website or be created by Jekyll during `jekyll build` from the sources. This could also be done via a git submodule.
* we have to deal with the ugly `linkCreator.sh`

`linkCreator.sh` creates PHP files that issue redirects. Do we need redirects? Wouldn't normal links suffice?

If we need it, there are other ways. We could

1. create HTML files that do redirect using `<meta http-equiv="refresh" … >` magic. See [here](https://www.w3.org/TR/WCAG20-TECHS/H76.html) and [here](https://en.wikipedia.org/wiki/Meta_refresh)
2. create an `.htaccess` file that instructs Apache to do issue the redirects

The first option would also work on GitHub Pages, the second option would be a direct and much nicer replacement of the current solution.

**Comment by sebschrader** [comment]
I'll considers this completed.
