### ISSUE TITLE
Content update for 2016

### ISSUE THREAD

**Issue by JustusAdam** [fsr/ese-website#37]
The websites content needs to be updated for 2016.

**Comment by heisig** [comment]
4f4359cc6c09e2c06e4dd8196bcf0fb111550faa updated the german content for 2016. English content is yet to update.

**Comment by MarauderXtreme** [comment]
Is this finished or is there still something missing?

**Comment by heisig** [comment]
Es fehlt glaube ich noch der Zeitplan als  iCal-Datei. Ansonsten sind es dann Updates die später erst nötig sind (Tutoren-Foto, Stundenpläne, NoPanic PDF, etc.). Kann aber auch sein, dass ich etwas übersehen hab

**Comment by MarauderXtreme** [comment]
![INVESTIGATE!](https://img0.etsystatic.com/050/0/5847649/il_570xN.693550826_1nny.jpg)

**Comment by MarauderXtreme** [comment]
I think the ics gets generated by jekyll so we should be done with this.
