### ISSUE TITLE
Inlining the logo

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-website#38]
I've seen, that the logo has been updated with the new colour. Is there a svg version of the logo?  
If so, we could just inline the logo and color it via CSS. So we just need to change the colour every year and don't have to regenerate the logo.

**Comment by heisig** [comment]
I'll make a SVG Version tomorrow

**Comment by MarauderXtreme** [comment]
Well. I think a few days are over now. Still nothing to see.

**Comment by heisig** [comment]
Jep, das tut mir auch leid. Ich hatte damals mal schnell geschaut wie ich das löse, aber keine gute Variante entdeckt die ich fix umsetzen kann. Da die Priorität nicht wirklich hoch ist, habe ich das mal ausgelassen da ich einige andere Dinge um die Ohren hab.

**Comment by MarauderXtreme** [comment]
Okay. Thanks for the update.  
What do you think? Is this a thing for 2016 or is it postponed for future releases?

**Comment by heisig** [comment]
Ab nächster Woche habe ich wieder mehr Zeit, bin aber auch im Urlaub. Ich denke mal, dass ich das vielleicht im September angehen kann. Sofern das nicht jemand anderes machen möchte. Also potentiell schon noch für 2016

**Comment by MarauderXtreme** [comment]
Thank you for creating this version but there are some flaws with it.

1. The 6 of the year looks somehow mishappened. I think it's the wrong font-family.
2. The ratio of the image is not 1:1. This somehow breaks the layout in some corner cases.
3. The picture is 200x183px. The old one was 270x270px. Chrome scales the image up while Firefox leaves it by it's original proportions. So I think we need a svg with at least 270x270px or bigger.

It would be great if that can be fixed. I created the` svg-logo` branch, where everything can go in.

**Comment by heisig** [comment]
Hmm, die 6 sieht bei mir auf den ersten Blick in Ordnung aus. Ich schau aber nochmal genau.
Beim aktuellen Logo ist einfach noch ein bisschen Rand an den Seiten, dass es 1:1 ist. Werde ich anpassen.
Ansonsten sprichst du aber schon vom SVG, oder? Den das ist eine Vektorgrafik die keine Pixel hat..
Bin etwas verwirrt gerade

**Comment by sjmielke** [comment]
Die `6` ist ein Textobjekt, die anderen Ziffern Pfade. Und da Chris vermutlich Haettenschweiler nicht aufm Rechner hat schlägts nur bei ihm fehl würd ich mal behaupten.

**Comment by MarauderXtreme** [comment]
Ah okay. That probably explains it. Linux FTW. ^^

Well the svg has a height and a width defined. Have a look into lines 16 and 17.

It would be great if we could edit this svg in a way we just have to update the last 2 digits of the year and then just change the color. Maybe I will move it to includes and let jekyll handle this.

**Comment by heisig** [comment]
Ich passe es gerade an. Die Änderung über den SVG-Code wäre schön, aber da besteht dann doch das gleiche Problem, dass die Schriftart fehlt.

**Comment by MarauderXtreme** [comment]
The font problem is solvable by serving the font via the webserver. (ttf,eot,woff, whatever) So we don't have the problem anymore an we could easily change the colors and year by just updating the _config.yml
I will just throw some example code to the mentioned branch later.

**Comment by MarauderXtreme** [comment]
Have a look at the changes in branch `svg-logo`. I think this will do it. The only thing missing is the text element.

**Comment by MarauderXtreme** [comment]
For the text element you can either use the complete year `{{ site.year }}` or filter it with `{{ site.year | remove: "20" }}`

**Comment by sjmielke** [comment]
1. #overengineering
2. Haben wir die Rechte, Haettenschweiler einfach so in einem Open-Source-Projekt zu distribuieren? (Tipp: Nein.)

**Comment by MarauderXtreme** [comment]
Look at the 2016 milesrone. It is now past due by 11 days. There was enough time to fix everything in it. So I think it is a great idea to automate as much as possible.

Regarding the font. Why choose it in the first place or maybe why not "unproprietar" the logo so that the is no problem. Something looking similar.

**Comment by heisig** [comment]
Das Logo wurde ca. 2008-2009 so gestaltet und seit dem nicht nur für die Webseite genutzt. Wie du vielleicht weißt, findet es sich auf den Tassen, T-Shirts sowie der NoPanic wieder und muss dafür eh jedes Jahr mit einer Vektorgrafik-Software angefasst werden.
Eine grundlegende Veränderung ist dann nicht mal so schnell gemacht und gewollt.
Meiner Meinung nach sieht das Logo so gut aus und hat Wiedererkennungswert. Es wäre extrem schade, wenn die Tassen sich jetzt ändern würden. Sieht dann einfach blöd aus im Regal.
Dieses Jahr ist der Zug eh abgefahren :train: 

_Irgendwie hatte ich das Issuse auch anders in Erinnerung. Dachte es geht primär darum, dass PNG auszutauschen weil wir eh ne Vektorgrafik haben.._

**Comment by MarauderXtreme** [comment]
My intent was to inline the logo so we could just use `.ese-logo > svg path {fill: $year-color}` so that the colorisation is easily done. I forgot about the year.

Have a look at https://www.onlinewebfonts.com/download/97d6f29a4bda3a872dad26cc5b2d0d7b
I think as long we use their links it is okay for us regarding licensing.

**Comment by heisig** [comment]
Ich bin kein Experte, aber denke nicht, dass es dadurch lizenzrechtlich ok ist.
Die Font ist von Microsoft und kostet Geld. Eine Server-Lizenz direkt mal 390$ pro Jahr.
Diese WebFont-Anbieter lassen Nutzer einfach Schriftarten hochladen. Oft sind das dann kopierte geschützte Schriftarten wo die Copyright Anmerkungen entfernt wurden.

**Comment by JustusAdam** [comment]
Very unfortunate the year isn't actually text, otherwise we could insert it via jekyll.
