### ISSUE TITLE
Tabe is being incorrectly displayed in english mobile view

### ISSUE THREAD

**Issue by JustusAdam** [fsr/ese-website#41]
The timetable is rendered as a list in english on mobile, rather than the desired table.

**Comment by Hannibal42** [comment]
The problem appears after a switch from on language to the other

**Comment by xamm** [comment]
Fixed issue with commit c2d3c582a1ffa0b48c2518291fad621554f4a9d8

**Comment by xamm** [comment]
The issue is now done . But is it intended that the barrier-free schedule is a list in all views?

**Comment by MarauderXtreme** [comment]
If you can fix a table to be barrier-free than you are welcome to do this.  
IMO the list version should be standard for mobile. The table breaks everything.

**Comment by xamm** [comment]
> IMO the list version should be standard for mobile. The table breaks everything.  <

So the issue would be the german site displaying the table as standard. And the english site was correctly displaying the list.

**Comment by MarauderXtreme** [comment]
Well. I heard there was a discussion within the ifsr and they decided, that they want the table on mobile too. (Although it breaks everything on mobile).  
I think Justus forgot to change it in English too after he switched it in German.  
As I stated: In my opinion and also one of my colleague as web devs this is no good design. But okay.

**Comment by JustusAdam** [comment]
I agree it is bad design but was explicitly requested.

As far as I can see this issue can be closed.
