### ISSUE TITLE
Evaluate Jekyll-Assets

### ISSUE THREAD

**Issue by sebschrader** [fsr/ese-website#42]
In #19 we discussed that it would be great, if our assets had URLs that are be based on a digest (e.g. SHA-1) of their contents, so that they could be cached forever. As a workaround we're using the commit hash.

The downside of the commit hash is obviously that it is not based on the file contents and that it changes with every commit.

[Jekyll-Assets](https://github.com/jekyll/jekyll-assets), which is part of the Jekyll project, but not part of the default Jekyll distribution, does exactly what we need and much more useful things.

I can't estimate how difficult it would be to start using Jekyll-Assets. What are your opinions?

**Comment by JustusAdam** [comment]
Probably incompatible with the preview stuff on gut hub pages.

**Comment by sebschrader** [comment]
What about deploying to GitHub pages manually?

**Comment by JustusAdam** [comment]
Somewhat defeats the point but possible.

**Comment by kiliankoe** [comment]
The gh-pages stuff was only for previewing the dev version, correct? Nice to have, but definitely not necessary.

**Comment by sebschrader** [comment]
> Somewhat defeats the point but possible.

I don't agree. GitHub just makes it very easy for you if you use a restricted Jekyll configuration.

You can build any site yourself with Jekyll or any other static site generator, it's just not as easy as pointing a `gh-pages` branch to your desired revision and letting GitHub do the rest for you.

The Jekyll guys themselves [do it like this](https://github.com/jekyll/jekyll/tree/gh-pages).

> I thought that gh-pages works as a staging server where new features can be tested and reviewed.

This would still be possible. The only requirement would be that you would have to have Jekyll and everything else installed locally on your machine to create a build.

**Comment by 7HAL32** [comment]
Done. 🎉
