### ISSUE TITLE
Add Video from last year as motivation

### ISSUE THREAD

**Issue by SaschaPeukert** [fsr/ese-website#46]
I suggest adding 

https://www.youtube.com/watch?v=fMlOaVGz4T8

as motivation for the new students (perhaps on the pictures page (Rename to media?) or somewhere)

**Comment by MarauderXtreme** [comment]
Isn't there a video from last year. I think that would fit better.  But it is a cool Idea.

**Comment by SaschaPeukert** [comment]
I would agree with you but that one isn't any good. If anyone would get me the source material from last year, i could try to mend that mess. But since i nobody answered that plea (as of the several times i asked it),  i'll say that nobody really cares :-(

**Comment by kiliankoe** [comment]
I actually think the one from last year's day one is fine. Of course it'd be nice to show more than that but I enjoyed it nonetheless.

**Comment by MarauderXtreme** [comment]
Provide link.

**Comment by SaschaPeukert** [comment]
Here you go:
https://vimeo.com/141549237

Btw: I still hate that 50% of this video is just a mudd blur effect

**Comment by MarauderXtreme** [comment]
Okay. I will look into it and embedd it.

**Comment by MarauderXtreme** [comment]
Have a look at #48
