### ISSUE TITLE
Table heading is being incorrectly displayed in portrait mode

### ISSUE THREAD

**Issue by ghost** [fsr/ese-website#47]
<strong>The timetable-heading is too short.</strong> 
The heading is not displayed over the Friday and Saturday column.

<img width="403" alt="timetable-heading" src="https://cloud.githubusercontent.com/assets/10974298/17649193/92f676dc-622e-11e6-97a4-009ab022dcb8.png">

**Comment by kiliankoe** [comment]
While on this: Would it be an idea to shorten the weekday table headers to abbreviations? Mo, Di, etc. 

This has nothing to do with this issue, sorry.

**Comment by MarauderXtreme** [comment]
That is the problem with tables on mobile. It overflows the grid. You can try and correct the classes, so that the accordion is as far as the table.  
This thing is not a heading but the tab of the accordion. (This is the only thing displayed correctly in this picture at the moment. ^^)
