### ISSUE TITLE
English Index is listed in menu

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-website#50]
I don't know if this is a problem since last year but somehow the index is listed as a link within the menu. This only happens if english is the current language. Maybe @JustusAdam can have a look at this later.

**Comment by MarauderXtreme** [comment]
Okay. Well it seems like it was a fault on my site. Nevermind.

**Comment by heisig** [comment]
Ich bin mir nicht sicher ob du das mit dem Issue meintest aber ein Problem hinsichtlich des englischen Menüs besteht immer noch. Und zwar ist auf den englischen Seiten der Link zum Index (der ganz links) falsch und leitet wieder auf die deutsche Seite zurück.
