### ISSUE TITLE
Announce Hiking trip

### ISSUE THREAD

**Issue by jgonsior** [fsr/ese-website#51]
Could you please put the following text on the website?
German:
Dresden besteht nicht nur aus Stadt, die Umgebung bietet auch ein herrliches Naturpanorama. Eng verbunden mit Dresden ist die Sächsische Schweiz, eine Wanderung hier ist schon ein muss für jeden Studenten hier. Drum nutzen wir noch die verbliebenen guten Herbststunden um dem gerecht zu werden. Treffpunkt ist am Samstag dem 15.10.16 am Dresdner Hauptbahnhof Gleis 18, wo wir 8:29 mit der S1 gemeinsam nach Krippen fahren werden. Vergesst nicht euren Studentenausweis (als Zugticket)! Ansetzen würden wir rund fünf Stunden plus Pausen, nehmt euch genug Verpflegung mit. Zurück geht es von Schmilka wieder mit Fähre und Bahn nach Dresden.

English: 
Dresden isn't known only for the old town but as well for the beautiful hiking paradise, the Sächsische Schweiz. We'll meet on Saturday, the 15th of October, at the train station "Dresden Hauptbahnhof", platform 18, and we'll take the train S1 in the direction of Krippen at 8:29. Don't forget your student ID, it is your train ticket! It'll take us approximately five hours excluding breaks, so don't forget enough food for the day. We'll go back from Schmilka with the ferry and train.

**Comment by MarauderXtreme** [comment]
Where? As news or which page?

**Comment by jgonsior** [comment]
News sounds fine. Either that or somewhere close to the schedule, like directly under it for example?

**Comment by heisig** [comment]
Ah verdammt. Ich bin auch gerade dran.. Ich würde die Wanderung allerdings ungerne als News machen sondern sie gleich in den Zeitplan aufnehmen und die Beschreibung drunter packen.

(ich pushe gleich auch noch andere commits)
