### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by lucaswo** [fsr/ese-website#53]
Opening the website results in Content Security Policy violations. Most of them are image-related, so the maps and images do not appear.

Like:
- `Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf http://staticmap.openstreetmap.de/staticmap.php?center=51.0484,13.7570&zoom=16&size=655x400&markers=51.0484,13.7570,ol-marker blockiert ("img-src https://ese.ifsr.de")`
- `Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://ese.ifsr.de/2016/css/img/desaturate.svg blockiert ("default-src 'none'")`

I've searched the repo for security policies, but didn't find any.

Apparently this error does not appear in the version on gh-pages.

Tested with FF 48.0.2 and Chrome 52.0.2743.116 m

**Comment by dirkonet** [comment]
Content Security Policy headers are set in the server configuration, guess you have to ask root@. github's servers have a different config.

**Comment by heisig** [comment]
Das Video scheint hiervon betroffen zu sein und wird deswegen nicht angezeigt

**Comment by Feliix42** [comment]
Peeked into my browsers Error Log:

```
[Error] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (2016, line 0)
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.woff because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.ttf because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.svg because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy. (2016, line 1, x2)
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.woff because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.ttf because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.svg because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy. (2016, line 1, x2)
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.woff because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.ttf because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.svg because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.woff because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.ttf because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load https://ese.ifsr.de/2016/vendor/slick/fonts/slick.svg because it appears in neither the font-src directive nor the default-src directive of the Content Security Policy.
[Error] Refused to load data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs= because it does not appear in the img-src directive of the Content Security Policy. (x7)
[Error] Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy. (2016, line 1)
[Error] Refused to load data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs= because it does not appear in the img-src directive of the Content Security Policy.
```

**Comment by sebschrader** [comment]
I've taken care of the errors I could get in Firefox and Chromium. Due to a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=878608) `desaturate.svg` can't be loaded yet.

I would have to specify a `default-src` that is not `none` for that.

**Comment by MarauderXtreme** [comment]
This is only a warning but can this be fixed to?
`Content Security Policy: Die Direktive 'frame-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.`

**Comment by sebschrader** [comment]
I left it in intentionally, because `frame-src` is CSP 1.0 and `child-src` is CSP 2.0.

Safari 9.0 for example supports only `frame-src`.

**Comment by MarauderXtreme** [comment]
Okay. Thanks for clarification.

**Comment by MarauderXtreme** [comment]
Unfortunately we have again the issue for the new slideshow. https://ese.ifsr.de/2016/fotos.html
Either we remove the Slideshow iframe to prevent this free space or one of the roots needs to update the server settings.

**Comment by heisig** [comment]
Ist mir bekannt. Ich hatte nach dem Release leider keine Zeit mehr irgendwas zu machen. Bzw. habe immer noch keine Zeit.
Server updated das es passt wäre schön, ansonsten verlinken wir die Slideshow halt auch erstmal

**Comment by MarauderXtreme** [comment]
The link exists. Only the blank space is a bit annoying.

**Comment by heisig** [comment]
Das ist der Link zur Galerie, nicht zur Slideshow. Da ist noch ein kleiner Unterschied

**Comment by sebschrader** [comment]
I can update it, so that it works for now, but the slideshow should really be part of the website and not sitting in some `~user` folder.
