### ISSUE TITLE
Barely readable content

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-website#54]
With the new color the links and content are barely readable. White on yellow isn't the greatest idea.

**Comment by MarauderXtreme** [comment]
To prevent this, I changed the code that it will invert the background color. Maybe it's not the best solution but the best for automation.
51f5fa816a5a7b90433dc0788d2cc24dbabdfb0a

**Comment by heisig** [comment]
Ähm, d.h. du hast die Textfarbe bei gelben Hintergründen auf Schwarz gesetzt?
Da gab es schon eine interne Disskussion zu.. Ergebnis: lieber etwas schlechtere Lesbarkeit als Dynamo bzw. DVB Look der Webseite

**Comment by MarauderXtreme** [comment]
Well the inverted color is some kind of blue (#023BED). It get's calculated by a scss function. So we don't have to think about it next year if the colour changes again drastically.
If it isn't desired than I will revert the changes but merge the PR because there were some slight changes in the breakpoints and language switcher.

**Comment by heisig** [comment]
Merged. Bitte setz aber die Farbe vorerst zurück. Danke!

**Comment by MarauderXtreme** [comment]
Hopefully next year a better colour will be chosen.

**Comment by kiliankoe** [comment]
![](http://i.giphy.com/3o6Zt2l7JNe272QpqM.gif)
