### ISSUE TITLE
Provide OpenStreetMap map images via HTTPS

### ISSUE THREAD

**Issue by sebschrader** [fsr/ese-website#57]
While taking care of #53 I noticed that the OpenStreetMap map images are plain HTTP links.

Please find a way to provide the maps over HTTPS, so that we don't get mixed content warnings.

**Comment by heisig** [comment]
Hilfreicher Link: http://wiki.openstreetmap.org/wiki/Static_map_images

ich kann mir das jetzt allerdings nicht  anschauen - leider keine Zeit

**Comment by kiliankoe** [comment]
Afaik kann der [staticMapLite](http://staticmap.openstreetmap.de) Server kein SSL.

**Comment by MarauderXtreme** [comment]
We can save the images into the project and serve them. Every other service either requires some kind of access/auth token or has no https.

**Comment by sebschrader** [comment]
I found a staticMapLite [instance hosted by the FAU](https://osm.rrze.fau.de/) that serves HTTPS:

![](https://osm.rrze.fau.de/staticmaplite?center=51.0254,13.7232&zoom=16&size=655x400&markers=51.0254,13.7232,ol-marker)

![](https://osm.rrze.fau.de/staticmaplite?center=51.0484,13.7570&zoom=16&size=655x400&markers=51.0484,13.7570,ol-marker)

![](https://osm.rrze.fau.de/staticmaplite?center=51.0301,13.7540&zoom=16&size=655x400&markers=51.0301,13.7540,ol-marker)

**Comment by kiliankoe** [comment]
`https://osm.rrze.fau.de/staticmaplite?center=51.0254,13.7232&zoom=16&size=655x400&markers=51.0254,13.7232,ol-marker`

`https://osm.rrze.fau.de/staticmaplite?center=51.0484,13.7570&zoom=16&size=655x400&markers=51.0484,13.7570,ol-marker`

`https://osm.rrze.fau.de/staticmaplite?center=51.0301,13.7540&zoom=16&size=655x400&markers=51.0301,13.7540,ol-marker`

Your images are being rehosted by github masking the url for quick copypasta ;)

**Comment by sebschrader** [comment]
I know, but I thought people would just use the source code of my comment.

**Comment by MarauderXtreme** [comment]
If we want to self host, you just need to accept the PR of me.

**Comment by sebschrader** [comment]
IDK honestly, but self-hosting is more independent.
