### ISSUE TITLE
Link to GitHub

### ISSUE THREAD

**Issue by JustusAdam** [fsr/ese-website#60]
I think it would be sensible to add a reference to this repo on the site with a text that reads something like "Found an error on the site? Open an Issue or send us a pull request in the GitHub repository"

**Comment by dirkonet** [comment]
We already have a link to the fsr organization on GitHub in the footer. Maybe just change that? I'm not really sure why we are linking to the organization anyway.

**Comment by JustusAdam** [comment]
Yes we have that link because the base theme we used had it 😄. I'm not necessarily agains having it there for people who know what GitHub is that might be interesting.

What I'm talking about is more a link to the bug tracker and source code so people can submit bugs if they find them. I always highly appreciate it when a website has it. And I personally am often interested in a websites source so I love these kinds of links.

**Comment by sebschrader** [comment]
It would also be useful, if the specific commit ID is shown in the production version on the kaki as well as on the gh-pages version.

**Comment by JustusAdam** [comment]
I agree but there was some issue with the jekyll plugin we used to get that commit id i think ... not sure though.

**Comment by sebschrader** [comment]
I think the “problem” was that that you have to use a different plugin for GitHub than for a local Git repository, but apparently you can also use the Jekyll GitHub metadata plugin locally:

https://help.github.com/articles/repository-metadata-on-github-pages/#using-repository-metadata-locally

**Comment by sebschrader** [comment]
Our `_config.yml` misses that line.
