### ISSUE TITLE
FAQ für die schlimmen Fragen nach der ESE

### ISSUE THREAD

**Issue by heisig** [fsr/ese-website#62]
- Ich war nicht bei der ESE, was ist hier los?
- Ich war nicht bei der Einschreibung - war das wichtig?
- Was ist mit der EMI Übung da in der 6. DS?
- Warum ist der Stundenplan auf jExam nicht vollständig?
- Wann fängt meine Übung an?
- Hilfe!!!!

**Comment by MarauderXtreme** [comment]
Well. Write a news entry and there we go.

**Comment by heisig** [comment]
War an sich für die Zukunft gedacht und vorerst ne fixe Idee. Wenn sich natürlich schon jetzt genug Inhalte finden können wir das auch noch in die aktuelle Version einbauen
