### ISSUE TITLE
Legal information

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-website#65]
German law requires us to provide an imprint and contact address.
Idea: Just link to iFSR imprint.

**Comment by JustusAdam** [comment]
Do we even have an Imprint and a contact on ifs.de? If not, do we have to?

**Comment by kiliankoe** [comment]
Contact is here: https://www.ifsr.de/fsr:kontakt

**Comment by MarauderXtreme** [comment]
As I understand it you need explicit sites for Imprint, Privacy Policy and a Disclaimer. So it is not sufficient to say, we have something in the sidebar. We need something that states who is in charge. (§5 TMG)
It is okay to link an imprint from another site but it needs to be an imprint.
