### ISSUE TITLE
Barrier-free timetable not working

### ISSUE THREAD

**Issue by jgonsior** [fsr/ese-website#77]
The link to exchange the fancy HTML table schedule and the barrier-free one is doing kind of nothing right now, or at least not in the by me tested browsers (Firefox, Chrome, Opera, Vivaldi).

**Comment by 7HAL32** [comment]
Yep, already fixed on branch development. Working result at https://fsr.github.io/ese-website/. This will hopefully be released to https://ese.ifsr.de/2017/ today.
