### ISSUE TITLE
Outdated favicon

### ISSUE THREAD

**Issue by jgonsior** [fsr/ese-website#78]
It would be nice to recolor the favicon from yellow to blue.

**Comment by 7HAL32** [comment]
Yep, already on the list. But thanks for having a close look at the website anyway. :)

**Comment by MarauderXtreme** [comment]
Looking at the website it looks like the favicon has been changed but other icons have been left out? Is this intended? Then we should at least remove the metatags in head to show the change.

**Comment by 7HAL32** [comment]
No, this is not intended but simply a time issue. Feel free to help out here :)

**Comment by MarauderXtreme** [comment]
Okay. Can you point me to the original logo file? I seem to cannot find it right now.

**Comment by 7HAL32** [comment]
![PNG](https://user-images.githubusercontent.com/11499680/30798797-1e1ec0e2-a1db-11e7-9a4f-109ef3d28911.png)

**Comment by 7HAL32** [comment]
Any update on this?

**Comment by MarauderXtreme** [comment]
I planned to regenerate them tomorrow. I forgot about it yesterday.

**Comment by MarauderXtreme** [comment]
See #83
